products = [
    (product1 = {
        name: "KYRRE 쉬레",
        category: "chair",
        picture: "/project/image/chair/KYRRE 쉬레1.jpg",
        price: 19900,
        sale: 0,
        amount: 100,
        info: "세 개의 곡선형 다리가 있는 만능 스툴은 갑자기 손님이 들렀을 때나 책 또는 음료를 둘 공간이 더 필요할 때 아주 유용해요",
    }),
    (product2 = {
        name: "POANG 포엥",
        category: "chair",
        picture: "/project/image/chair/POANG 포엥1.jpg",
        price: 99900,
        sale: 0,
        amount: 1,
        info: "높은 등받이가 목을 편안하게 받쳐줍니다.",
    }),
    (product3 = {
        name: "MARTIN 마르틴",
        category: "chair",
        picture: "/project/image/chair/MARTIN 마르틴1.jpg",
        price: 29900,
        sale: 0,
        amount: 0,
        info: "의자를 포개둘 수 있어서 보관할 때 공간을 많이 차지하지 않습니다.",
    }),
    (product4 = {
        name: "ORFJALL 외르피엘",
        category: "chair",
        picture: "/project/image/chair/ORFJALL 외르피엘1.jpg",
        price: 49900,
        sale: 0,
        amount: 1,
        info: "심플한 어린이용 책상 의자입니다.",
    }),
    (product5 = {
        name: "TOBIAS 토비아스",
        category: "chair",
        picture: "/project/image/chair/TOBIAS 토비아스1.jpg",
        price: 129000,
        sale: 0,
        amount: 1,
        info: "주변 모습을 비춰주는 투명한 의자입니다. 방 안의 색상을 흡수해서 마치 의자가 공중에 떠있는 것처럼 보이죠. 의자 시트 재질도 유연해서 앉는 사람 기분까지 가볍게 만들어 줍니다.",
    }),
    (product6 = {
        name: "BALTSAR 발트사르",
        category: "chair",
        picture: "/project/image/chair/BALTSAR 발트사르1.jpg",
        price: 199000,
        sale: 0,
        amount: 1,
        info: "실용적이고 편안한 회전 기능을 통해 의자를 움직이지 않고 식탁에서 쉽게 일어날 수 있어요.",
    }),
    (product7 = {
        name: "ANGERSBY 앙에르스뷔",
        category: "sofa",
        picture: "/project/image/sofa/ANGERSBY 앙에르스뷔1.jpg",
        price: 229000,
        sale: 0,
        amount: 1,
        info: "마음에 드신다면 지금 바로 구매해서 집으로 가져가세요. ANGERSBY 앙에르스뷔 소파는 차에 실어서 집까지 편하게 운반할 수 있도록 만들어졌습니다. 측면에 수납할 수 있는 포켓이 있어 더욱 편리합니다.",
    }),
    (product8 = {
        name: "SODERHAMN 쇠데르함",
        category: "sofa",
        picture: "/project/image/sofa/SODERHAMN 쇠데르함1.jpg",
        price: 699000,
        sale: 0,
        amount: 1,
        info: "스타일리시하고 산뜻한 느낌이 좋다면 시트가 깊고 넓은 소파는 어떨까요? 개성을 살려 맞춤 구성한 SODERHAMN 쇠데르함 소파에 혼자 또는 가족 모두와 함께 앉아 편안한 휴식을 즐겨보세요.",
    }),
    (product9 = {
        name: "KLIPPAN 클리판",
        category: "sofa",
        picture: "/project/image/sofa/KLIPPAN 클리판1.jpg",
        price: 299000,
        sale: 0,
        amount: 1,
        info: "IKEA는 1980년대에 KLIPPAN/클리판 소파를 출시했으며 지금까지 인기를 끌고 있습니다. 이 소파는 편안하고 거의 모든 곳에서 사용할 수 있으며 수많은 커버를 선택할 수 있는 옵션이 있습니다. 모던하며 유행을 타지 않는 클래식한 스타일입니다!",
    }),
    (product10 = {
        name: "FRIHETEN 프리헤텐",
        category: "sofa",
        picture: "/project/image/sofa/FRIHETEN 프리헤텐1.jpg",
        price: 649000,
        sale: 0,
        amount: 1,
        info: "푹 주무셨나요? 간밤에 사용했던 침실이나 게스트룸이 순식간에 넓은 거실로 변신할 수 있어요. 빌트인수납장에 침구, 책, 파자마를 담기만 하면 된답니다.",
    }),
    (product11 = {
        name: "GRONLID 그뢴리드",
        category: "sofa",
        picture: "/project/image/sofa/GRONLID 그뢴리드1.jpg",
        price: 1249000,
        sale: 0,
        amount: 1,
        info: "긴의자는 좌우 어디에든 놓을 수 있고 언제든지 위치를 바꿀 수 있습니다.",
    }),
    (product12 = {
        name: "LINANAS 리나네스",
        category: "sofa",
        picture: "/project/image/sofa/LINANAS 리나네스1.jpg",
        price: 499000,
        sale: 0,
        amount: 1,
        info: "이 커버는 폴리에스테르(폴리에스테르 원착) 소재의 VISSLE/비슬레 패브릭으로 제작됩니다. 매끄러운 직조와 멋진 투톤 효과가 있는 내구성 높은 소재입니다.",
    }),
    (product13 = {
        name: "NORDMYRA 노르드뮈라",
        category: "table",
        picture: "/project/image/table/NORDMYRA 노르드뮈라1.jpg",
        price: 398600,
        sale: 0,
        amount: 1,
        info: "이 제품에는 목재처럼 재생 가능한 소재를 사용해서 화석 연료나 유한 소재의 사용을 피했어요.",
    }),
    (product14 = {
        name: "LAGKAPTEN 락캅텐",
        category: "table",
        picture: "/project/image/table/LAGKAPTEN 락캅텐1.jpg",
        price: 148900,
        sale: 0,
        amount: 1,
        info: "다른 책상이나 서랍유닛과 함께 사용해 업무 공간을 넓힐 수도 있어요. 뒷쪽의 전선인출구에는 케이블을 보이지 않게 정리해보세요.",
    }),
    (product15 = {
        name: "FRIDNAS 프리드네스",
        category: "table",
        picture: "/project/image/table/FRIDNAS 프리드네스1.jpg",
        price: 129000,
        sale: 0,
        amount: 0,
        info: "플라스틱 소재의 다리받침을 사용하여 바닥에 흠집을 내지 않고 쉽게 옮길 수 있습니다.",
    }),
    (product16 = {
        name: "GAMLARED 감라레드",
        category: "table",
        picture: "/project/image/table/GAMLARED 감라레드1.jpg",
        price: 208800,
        sale: 0,
        amount: 1,
        info: "간결한 디자인과 튼튼한 소재의 제품 세트로 아늑한 아침식사 공간이나 작은 다이닝 공간에 좋습니다. 소나무 원목 소재여서 오랫동안 온 가족이 둘러앉아 식사하고 다양한 활동을 해도 변함없이 튼튼합니다.",
    }),
    (product17 = {
        name: "MALM 말름",
        category: "table",
        picture: "/project/image/table/MALM 말름1.jpg",
        price: 179000,
        sale: 0,
        amount: 1,
        info: "인출식 패널도 작업 공간으로 활용할 수 있습니다.",
    }),
    (product18 = {
        name: "VANGSTA 방스타",
        category: "table",
        picture: "/project/image/table/VANGSTA 방스타1.jpg",
        price: 269000,
        sale: 0,
        amount: 0,
        info: "내구성이 뛰어난 테이블로 많은 손님이 찾아오는 모임을 준비할 때 유용합니다. 한 사람이 쉽게 확장할 수 있으며, 다리가 테이블 모서리에 자리하고 있어서 의자를 놓을 공간도 충분합니다.",
    }),
    (product19 = {
        name: "NESTTUN 네스툰",
        category: "bed",
        picture: "/project/image/table/NESTTUN 네스툰1.jpg",
        price: 184000,
        sale: 0,
        amount: 1,
        info: "튼튼한 스틸구조와 그물 패턴의 침대헤드는 가볍고 발랄한 느낌을 줍니다. 다른 다양한 스타일의 가구와도 잘 어울리는 심플한 디자인이죠.",
    }),
    (product20 = {
        name: "GLADSTAD 글라스타드",
        category: "bed",
        picture: "/project/image/bed/GLADSTAD 글라스타드1.jpg",
        price: 519000,
        sale: 0,
        amount: 1,
        info: "쿠션형 침대프레임에 4개의 쿠션형 수납함이 있어 편안한 휴식 공간과 잠자리가 되는 동시에 침대 아래에 실용적인 수납공간을 제공합니다.",
    }),
    (product21 = {
        name: "VADHEIM 바드헤임",
        category: "bed",
        picture: "/project/image/bed/VADHEIM 바드헤임1.jpg",
        price: 799000,
        sale: 0,
        amount: 1,
        info: "TUFJORD 투피오르드와 함께라면 매일 밤이 기다려질 거예요. 몸을 감싸는 듯한 곡선형 침대헤드가 편안한 휴식을 도와주고, 여유로운 아침 시간을 더욱 포근하게 만들어줍니다. 아름다운 윤기가 흐르는 부드러운 벨벳이 고급스러운 느낌을 주죠.",
    }),
    (product22 = {
        name: "FLEKKE 플레케",
        category: "bed",
        picture: "/project/image/bed/FLEKKE 플레케1.jpg",
        price: 569000,
        sale: 0,
        amount: 0,
        info: "낮에는 소파, 밤에는 침대로 변신하죠. 싱글 또는 더블침대로. 넉넉한 크기의 서랍이 2개나 있어 이불, 베개, 린넨 등을 보관할 수 있습니다. 공간이 부족한 집에 꼭 맞는 스마트한 솔루션이죠.",
    }),
    (product23 = {
        name: "BRIMNES 브림네스",
        category: "bed",
        picture: "/project/image/bed/BRIMNES 브림네스1.jpg",
        price: 274000,
        sale: 0,
        amount: 1,
        info: "침대 옆판은 매트리스의 두께에 따라 위치를 조절할 수 있습니다.",
    }),
    (product24 = {
        name: "LEIRVIK 레이르비크",
        category: "bed",
        picture: "/project/image/bed/LEIRVIK 레이르비크1.jpg",
        price: 284000,
        sale: 0,
        amount: 1,
        info: "화이트 스틸 재질의 화려한 곡선이 돋보이는 제품입니다. 로맨틱한 스타일을 좋아하는 사람이라면 마음을 빼앗기지 않을 수 없죠. 아름다운 텍스타일과 베개로 침대를 마무리하면 매일 동화책처럼 환상적인 꿈을 꿀 수 있을 거예요.",
    }),
    (product25 = {
        name: "SMASTAD 스모스타드",
        category: "closet",
        picture: "/project/image/closet/SMASTAD 스모스타드1.jpg",
        price: 267000,
        sale: 0,
        amount: 0,
        info: "어떤 날은 활동적으로, 또 어떤 날은 근사하게. 아이가 어느 정도 자라면 복장에 대한 고민도 중요한 하루 일과에 속하게 됩니다. 이 옷장은 공간이 충분해서 그런 끊임없는 스타일 변화를 수용할 수 있어요.",
    }),
    (product26 = {
        name: "KLEPPSTAD 클렙스타드",
        category: "closet",
        picture: "/project/image/closet/KLEPPSTAD 클렙스타드1.jpg",
        price: 189000,
        sale: 0,
        amount: 1,
        info: "간편하고 스마트하죠! 기본 기능에 충실한 옷장이 필요할 때 사용하기 좋아요. 수납이 여전히 부족하다면 KLEPPSTAD 클렙스타드 시리즈의 다른 옷장을 추가해보세요.",
    }),
    (product27 = {
        name: "GODISHUS 고디스후스",
        category: "closet",
        picture: "/project/image/closet/GODISHUS 고디스후스1.jpg",
        price: 149000,
        sale: 0,
        amount: 1,
        info: "선반과 옷장레일을 두 가지 방법으로 배치할 수 있어요. 상단 옷장레일 및 하단 선반으로 배치하거나 옷장 상단에 둘 다 함께 배치할 수 있습니다.",
    }),
    (product28 = {
        name: "SUNDVIK 순드비크",
        category: "closet",
        picture: "/project/image/closet/SUNDVIK 순드비크1.jpg",
        price: 329000,
        sale: 0,
        amount: 1,
        info: "부드럽게 닫히는 완충장치가 달려있는 도어입니다.",
    }),
    (product29 = {
        name: "BRIMNES 브림네스",
        category: "closet",
        picture: "/project/image/closet/BRIMNES 브림네스1.jpg",
        price: 299000,
        sale: 0,
        amount: 1,
        info: "집은 가족을 보호하는 안전한 장소여야 합니다. 그래서 본 옷장 제품에는 벽 고정장치가 동봉되어 있습니다.",
    }),
    (product30 = {
        name: "NORDKISA 노르드키사",
        category: "closet",
        picture: "/project/image/closet/NORDKISA 노르드키사1.jpg",
        price: 279000,
        sale: 0,
        amount: 1,
        info: "옷장의 짧은 쪽 중 하나를 벽에 붙여서 실내칸막이를 만들 수 있습니다.",
    }),
    (product31 = {
        name: "ARSTID 오르스티드",
        category: "light",
        picture: "/project/image/light/ARSTID 오르스티드1.jpg",
        price: 29900,
        sale: 0,
        amount: 1,
        info: "세월이 흘러도 변치 않는 아름다움을 지닌 근사한 조명을 소개합니다. 시리즈에 포함된 조명 제품과 함께 사용해 은은하고 부드러운 불빛으로 방안을 가득 채우고 통일감 있는 인테리어를 연출해보세요.",
    }),
    (product32 = {
        name: "FORSA 포르소",
        category: "light",
        picture: "/project/image/light/FORSA 포르소1.jpg",
        price: 29900,
        sale: 0,
        amount: 0,
        info: "스틸 소재의 클래식한 작업등으로 매일을 밝혀보세요. 조명의 각도를 자유롭게 조절하여 원하는 곳에 빛을 비출 수 있어 책상과 침대, 소파에서 독서등으로 사용하기 좋습니다.",
    }),
    (product33 = {
        name: "TALLBYN 텔뷘",
        category: "light",
        picture: "/project/image/light/TALLBYN 텔뷘1.jpg",
        price: 129000,
        sale: 0,
        amount: 1,
        info: "TALLBYN 텔뷘 시리즈의 조명은 메탈과 입으로 불어 만드는 유리 소재로 만들어서 클래식하면서도 튼튼한 디자인이에요. 멋진 분위기를 연출하는 기능성 조명이죠. 집안에 추억을 떠올리게 하는 공간을 만들어보세요.",
    }),
    (product34 = {
        name: "TALLBYN 텔뷘(2)",
        category: "light",
        picture: "/project/image/light/TALLBYN 텔뷘(2)1.jpg",
        price: 69900,
        sale: 0,
        amount: 1,
        info: "TALLBYN 텔뷘 시리즈의 조명은 메탈과 입으로 불어 만드는 유리 소재로 만들어서 클래식하면서도 튼튼한 디자인이에요. 멋진 분위기를 연출하는 기능성 조명이죠. 집안에 추억을 떠올리게 하는 공간을 만들어보세요.",
    }),
    (product35 = {
        name: "TARNABY 테르나뷔",
        category: "light",
        picture: "/project/image/light/TARNABY 테르나뷔1.jpg",
        price: 26900,
        sale: 0,
        amount: 1,
        info: "전통식 등유 램프 디자인에서 영감을 받은 무드등 제품으로, 빛이 따뜻하고 부드럽습니다. 불빛이 나오는 전구를 직접 볼 수 있는 형태이며, 디머로 밝기 조절을 할 수 있습니다.",
    }),
    (product36 = {
        name: "SIMRISHAMN 심리스함",
        category: "light",
        picture: "/project/image/light/SIMRISHAMN 심리스함1.jpg",
        price: 79900,
        sale: 0,
        amount: 1,
        info: "SIMRISHAMN 심리스함 시리즈의 멋진 유리와 크롬 조명이에요. 집안 분위기를 멋지게 만들어 주는 모던한 느낌의 조명이죠. 단독으로 사용해 포인트를 주거나 시리즈의 다른 조명과 함께 사용해보세요.",
    }),
    (product37 = {
        name: "KARLPETTER 칼페테르",
        category: "chair",
        picture: "/project/image/chair/KARLPETTER 칼페테르1.jpg",
        price: 69900,
        sale: 0,
        amount: 1,
        info: "FIXA 바닥보호패드와 함께 사용해 아래의 표면이 마모되지 않도록 보호할 수 있습니다.",
    }),
    (product38 = {
        name: "GLOSTAD 글로스타드",
        category: "sofa",
        picture: "/project/image/sofa/GLOSTAD 글로스타드1.jpg",
        price: 145000,
        sale: 0,
        amount: 1,
        info: "작고 귀여운 소파로 좁은 공간에도 잘 어울립니다.",
    }),
    // (product = {
    //     name: "",
    //     category: "light",
    //     picture: "/project/image/light/1.jpg",
    //     price: ,
    //     sale: 0,
    //     amount: 1,
    //     info: "",
    // }),
];
